#!/bin/bash
################################################################################
#                     Copyright (C) 2017 by Christian Meeßen                   #
#                                                                              #
#                        This file is part of GMTScripts.                      #
#                                                                              #
#       GMTScripts is free software: you can redistribute it and/or modify     #
#     it under the terms of the GNU General Public License as published by     #
#           the Free Software Foundation version 3 of the License.             #
#                                                                              #
#      GMTScripts is distributed in the hope that it will be useful, but       #
#          WITHOUT ANY WARRANTY; without even the implied warranty of          #
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU       #
#                   General Public License for more details.                   #
#                                                                              #
#      You should have received a copy of the GNU General Public License       #
#      along with GMTScripts. If not, see <http://www.gnu.org/licenses/>.      #
#******************************************************************************#
set -e
setgmt
gmttest

if [ $# -lt 1 ]
then
  echo
  echo "Not enough arguments."
  echo
  echo "Usage: PlotGravWorld InputFile [PropertyColumn [HeaderLines]]"
  echo "       arguments in [] are optional"
  echo
  echo "PropertyColumn - If the InputFile contains multiple columns, this"
  echo "                 defines the column with the value to plot. Columns"
  echo "                 start counting at 0. Default is 2"
  echo "HeaderLines    - Number of header lines in input file"
  echo
  echo "Plots gravity map of the world for z in mGal, polar color scale and"
  echo "in Robinson projection."
  echo
  echo "Note that if header lines in the input file start with different"
  echo "characters, i.e. Petrel points with attributes files, you need to define"
  echo "the number of header lines."
  echo
  exit
elif [ $# -eq 1 ]
then
  InFile=$1
  column=2
  nHeader=""
elif [ $# -eq 2 ]
then
  echo "3"
  InFile=$1
  column=$2
  nHeader=""
elif [ $# -eq 3 ]
then
  InFile=$1
  column=$2
  nHeader="-hi$3"
else
  echo "Input arguments: $#"
fi

echo "Input file     : $InFile"
echo "Property column: $column"
echo "Header lines   : $nHeader"

# I10 - return -R
echo "Extract ROI"
ROI=$(gmt gmtinfo $InFile -I0.1)
ROID="-Rd"
#CScale=$(gmt gmtinfo $InFile -T1/$column)
echo "> $ROI"

zColMin=$(bc <<< "scale=1;($column+1)*2-2")
zColMax=$(bc <<< "scale=1;($column+1)*2-1")

echo "Extract min/max values"
# Get map extent and zvalues
tmp1=( `gmt gmtselect $InFile $ROI $nHeader | gmt gmtinfo -C | sed 's/\t/ /g'` )
xmin=${tmp1[0]}
xmax=${tmp1[1]}
ymin=${tmp1[2]}
ymax=${tmp1[3]}
zmin=${tmp1[$zColMin]}
zmax=${tmp1[$zColMax]}

echo "> x: $xmin - $xmax"
echo "> y: $ymin - $ymax"
echo "> z: $zmin - $zmax"

dX=$(bc -l <<< "$xmax-($xmin)")
dY=$(bc -l <<< "$ymax-($ymin)")
dZ=$(bc -l <<< "($zmax-($zmin))/20")

echo "Define symmetric color scale"
zminABS=$(bc -l <<< "sqrt($zmin*$zmin)")
zmaxABS=$(bc -l <<< "sqrt($zmax*$zmax)")
CScaleMin=$(bc -l <<< "if ($zminABS < $zmaxABS) -$zmaxABS else -$zminABS")
CScaleMax=$(bc -l <<< "if ($zminABS < $zmaxABS) $zmaxABS else $zminABS")
CScale="-T$CScaleMin/$CScaleMax/$dZ"
echo "> $CScale"
#CScale="-T$zmin/$zmax/$dZ"

echo "Define map formats"
map_width=10
map_height=$(bc <<< "scale=2;$dY/$dX*$map_width")
scale_dX=$(bc <<< "scale=2;$map_width/2")
out_name=$InFile.ps
out_format='png'

echo "Initiate plot"
gmt makecpt -Cpolar.cpt $CScale > colors.cpt
gmt pscontour $InFile -i0,1,$column $nHeader -I -Ccolors.cpt -JN0/$map_width -Rd -S -A- -K > $out_name # -W0.1p,black
#  -A0/2/4
# D - resolution
# N - political borders
# W - shorelines
#gmt pscoast -J -R -Di -Na/0.5p,black -O -P -K >> $out_name
gmt pscoast -J -R -A0/0/1 -Di -W0.1p,black -O -P -K >> $out_name
gmt psbasemap -R -J -Baf -BwNsE --MAP_GRID_CROSS_SIZE_PRIMARY=0p --MAP_ANNOT_ORTHO=W --MAP_TITLE_OFFSET=8p -O -K >> $out_name
gmt psscale -D$scale_dX/-0.2/$map_width/0.3h -Ccolors.cpt -Baf$dZ+l"Gravity / mGal" -Np --MAP_LABEL_OFFSET=0 -O >> $out_name

case "$out_format" in
bmp )
	ftpe='b';;
eps )
	ftpe='e';;
pdf )
	ftpe='f';;
jpg )
	ftpe='j';;
png )
	ftpe='g';;
* )
	ftpe='g';;
esac

gmt ps2raster -A -P -E400 -T$ftpe $out_name

rm colors.cpt
rm $out_name
rm gmt.history
rm gmt.conf
rm *.eps *.bb 2> /dev/null

echo "Done."
echo "Output file: $InFile.$out_format"
