#!/bin/bash
################################################################################
#                     Copyright (C) 2016 by Christian Meeßen                   #
#                                                                              #
#                         This file is part of Scripts                         #
#                                                                              #
#        Scripts is free software: you can redistribute it and/or modify       #
#     it under the terms of the GNU General Public License as published by     #
#           the Free Software Foundation version 3 of the License.             #
#                                                                              #
#      GMTScripts is distributed in the hope that it will be useful, but       #
#          WITHOUT ANY WARRANTY; without even the implied warranty of          #
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU       #
#                   General Public License for more details.                   #
#                                                                              #
#      You should have received a copy of the GNU General Public License       #
#       along with Scripts. If not, see <http://www.gnu.org/licenses/>.        #
################################################################################
#
# This script triangulates given (irregular) XYZ point data on a sphere and
# outputs a regular Lon Lat Z grid using GMT.
#

if [ $# -lt 7 ]
then
  echo
  echo "Usage: points2grid.sh FILE_IN XMIN XMAX YMIN YMAX SPACING FILE_OUT"
  echo
  echo "Interpolates irregular Lon Lat data on a sphere and outputs"
  echo "a regular Lon Lat Z grid."
  echo
  exit
else
  inFile=$1
  outFile=$7
  xmin=$2
  xmax=$3
  ymin=$4
  ymax=$5
  gridspacing=$6

  echo "$inFile"
  echo "*** Triangulate ***"
  gmt sphinterpolate $inFile -R$xmin/$xmax/$ymin/$ymax -i0,1s-1,2 -I$gridspacing -Gtriangle.grd

  echo "*** Convert grid to xyz ***"
  gmt grd2xyz triangle.grd > $outFile

  echo "*** Cleaning up ***"
  rm gmt.history
  rm triangle.grd
  echo "Done!"
fi
