#!/bin/bash
################################################################################
#                     Copyright (C) 2017 by Christian Meeßen                   #
#                                                                              #
#                         This file is part of Scripts                         #
#                                                                              #
#       GMTScripts is free software: you can redistribute it and/or modify     #
#     it under the terms of the GNU General Public License as published by     #
#           the Free Software Foundation version 3 of the License.             #
#                                                                              #
#      GMTScripts is distributed in the hope that it will be useful, but       #
#          WITHOUT ANY WARRANTY; without even the implied warranty of          #
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU       #
#                   General Public License for more details.                   #
#                                                                              #
#      You should have received a copy of the GNU General Public License       #
#       along with Scripts. If not, see <http://www.gnu.org/licenses/>.        #
################################################################################
# Default settings for gmt

gmt set --FONT_ANNOT_PRIMARY=6p \
        --FONT_ANNOT_SECONDARY=6p \
        --FONT_LABEL=7p \
        --FONT_TITLE=7p,Helvetica-Bold \
        --MAP_FRAME_PEN=0.5p \
        --MAP_LABEL_OFFSET=3p \
        --MAP_TICK_LENGTH_PRIMARY=1p \
        --MAP_TICK_LENGTH_SECONDARY=0.5p \
        --MAP_TITLE_OFFSET=7p \
        --PS_MEDIA=A4 \
        --PS_PAGE_ORIENTATION=portrait
