#!/bin/bash
################################################################################
#                     Copyright (C) 2017 by Christian Meeßen                   #
#                                                                              #
#                         This file is part of Scripts                         #
#                                                                              #
#       GMTScripts is free software: you can redistribute it and/or modify     #
#     it under the terms of the GNU General Public License as published by     #
#           the Free Software Foundation version 3 of the License.             #
#                                                                              #
#      GMTScripts is distributed in the hope that it will be useful, but       #
#          WITHOUT ANY WARRANTY; without even the implied warranty of          #
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU       #
#                   General Public License for more details.                   #
#                                                                              #
#      You should have received a copy of the GNU General Public License       #
#       along with Scripts. If not, see <http://www.gnu.org/licenses/>.        #
################################################################################
set -e
setgmt
gmttest

if [ $# -lt 1 ]
then
  echo
  echo "Not enough arguments."
  echo
  echo "Usage: PlotPoint InputFile [PointSize [PropertyColumn [HeaderLines]]]"
  echo "       arguments in [] are optional"
  echo
  echo "PointSize      - Point size in plot. Default: 0.1"
  echo "PropertyColumn - If the InputFile contains multiple columns, this"
  echo "                 defines the column with the value to plot. Columns"
  echo "                 start counting at 0. Default is 2"
  echo "HeaderLines    - Number of header lines in input file"
  echo
  echo "Plots regular grid data as points."
  echo
  echo "Note that if header lines in the input file start with different"
  echo "characters, i.e. Petrel points with attributes files, you need to define"
  echo "the number of header lines."
  echo
  exit
elif [ $# -eq 1 ]
then
  InFile=$1
  PointSize=0.1
  column=2
  nHeader=""
elif [ $# -eq 2 ]
then
  InFile=$1
  PointSize=$2
  column=2
  nHeader=""
elif [ $# -eq 3 ]
then
  InFile=$1
  PointSize=$2
  column=$3
  nHeader=""
elif [ $# -eq 4 ]
then
  InFile=$1
  PointSize=$2
  column=$3
  nHeader="-hi$4"
else
  echo "Input arguments: $#"
fi

# I10 - return -R
ROI=$(gmt gmtinfo $InFile -I0.1)
ROI_D=${ROI:2}
#CScale=$(gmt gmtinfo $InFile -T1/$column)

zColMin=$(bc <<< "scale=1;($column+1)*2-2")
zColMax=$(bc <<< "scale=1;($column+1)*2-1")

# Get map extent and zvalues
tmp1=(`gmtselect $InFile $ROI $nHeader | gmtinfo -C`)
xmin=${tmp1[0]}
xmax=${tmp1[1]}
ymin=${tmp1[2]}
ymax=${tmp1[3]}
zmin=${tmp1[$zColMin]}
zmax=${tmp1[$zColMax]}

echo "x range [$xmin ; $xmax]"
echo "y range [$ymin ; $ymax]"
echo "z range [$zmin ; $zmax]"

zminBCC=`echo ${zmin} | sed -e 's/[eE]+*/\\*10\\^/'`
zmaxBCC=`echo ${zmax} | sed -e 's/[eE]+*/\\*10\\^/'`

echo "zminBCC: $zminBCC"
echo "zmaxBCC: $zmaxBCC"

dX=$(bc -l <<< "$xmax-($xmin)")
dY=$(bc -l <<< "$ymax-($ymin)")
dZ=$(bc -l <<< "($zmaxBCC-($zminBCC))/20")

echo "dX: $dX"
echo "dY: $dY"
echo "dZ: $dZ"

CScale="-T$zmin/$zmax/$dZ"

map_width=10
map_height=$(bc <<< "scale=2;$dY/$dX*$map_width")
scale_dX=$(bc <<< "scale=2;$map_width/2")
out_name=$InFile.ps
out_format='png'

square_size=$(bc <<< "scale=10;sqrt(2)*($map_width/($dX/10-1))")

echo "Plot information"
echo "ROI: $ROI"
echo "Color scale $CScale"

gmt makecpt -Chaxby.cpt $CScale > colors.cpt
echo "psbasemap"
echo "> ROI: $ROI"
echo "> ROI_D: $ROI_D"
echo "> map_width: $map_width"
echo "> map_height: $map_height"
gmt psbasemap $ROI -JX$map_width/$map_height -D$ROI_D+g'0/0/0' -K > $out_name
#gmt pscontour $InFile -i0,1,$column $nHeader -I -Ccolors.cpt -J -R -S -W0.1p,black -A- -K -O >> $out_name
gmt psxy $InFile -i0,1,$column $nHeader -Ss$PointSize -Ccolors.cpt -R -J -O -K >> $out_name
gmt psbasemap -R -J -Baf -BwNsE --MAP_GRID_CROSS_SIZE_PRIMARY=0p --MAP_ANNOT_ORTHO=W --MAP_TITLE_OFFSET=8p -O -K >> $out_name
gmt psscale -D$scale_dX/-0.2/$map_width/0.3h -Ccolors.cpt -Baf$dZ+l"Value" -Np --MAP_LABEL_OFFSET=0 -O >> $out_name

case "$out_format" in
bmp )
	ftpe='b';;
eps )
	ftpe='e';;
pdf )
	ftpe='f';;
jpg )
	ftpe='j';;
png )
	ftpe='g';;
* )
	ftpe='g';;
esac

gmt psconvert -A -P -E400 -T$ftpe $out_name

rm colors.cpt $out_name gmt.history gmt.conf *.eps *.bb 2> /dev/null

echo "Done."
echo "Output file: $InFile.$out_format"
