#!/bin/bash
################################################################################
#                     Copyright (C) 2014 by Christian Meeßen                   #
#                                                                              #
#                        This file is part of GMTScripts.                      #
#                                                                              #
#       GMTScripts is free software: you can redistribute it and/or modify     #
#     it under the terms of the GNU General Public License as published by     #
#           the Free Software Foundation version 3 of the License.             #
#                                                                              #
#      GMTScripts is distributed in the hope that it will be useful, but       #
#          WITHOUT ANY WARRANTY; without even the implied warranty of          #
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU       #
#                   General Public License for more details.                   #
#                                                                              #
#      You should have received a copy of the GNU General Public License       #
#      along with GMTScripts. If not, see <http://www.gnu.org/licenses/>.      #
#******************************************************************************#
# This script triangulates given (irregular) XYZ point data and outputs a regular
# XYZ grid using GMT.
#
if [ $# -lt 7 ]
then
  echo
  echo "Usage: points2grid FILE_IN XMIN XMAX YMIN YMAX SPACING FILE_OUT"
  echo
  echo "Triangulates given irregular XYZ point data and outputs a regular"
  echo "XYZ grid. For spherical interpolation use points2gridsphere"
  echo
  exit
else
  inFile=$1
  outFile=$7
  xmin=$2
  xmax=$3
  ymin=$4
  ymax=$5
  gridspacing=$6

  echo "$inFile"
  echo "*** Triangulate ***"
  gmt triangulate "$inFile" -R$xmin/$xmax/$ymin/$ymax -I$gridspacing -Gtriangle.grd

  echo "*** Convert grid to xyz ***"
  gmt grd2xyz triangle.grd > "$outFile"

  echo "*** Cleaning up ***"
  rm gmt.history triangle.grd
  echo "Done!"
fi
