#!/bin/bash
################################################################################
#                     Copyright (C) 2017 by Christian Meeßen                   #
#                                                                              #
#                         This file is part of Scripts                         #
#                                                                              #
#       GMTScripts is free software: you can redistribute it and/or modify     #
#     it under the terms of the GNU General Public License as published by     #
#           the Free Software Foundation version 3 of the License.             #
#                                                                              #
#      GMTScripts is distributed in the hope that it will be useful, but       #
#          WITHOUT ANY WARRANTY; without even the implied warranty of          #
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU       #
#                   General Public License for more details.                   #
#                                                                              #
#      You should have received a copy of the GNU General Public License       #
#       along with Scripts. If not, see <http://www.gnu.org/licenses/>.        #
################################################################################
set -e
version=`gmt --version`

if [[ $# -eq 0 ]]
then
    if [[ $version == "5.3"* ]]
    then
        echo "GMT >= 5.3 found"
    else
        echo "ERROR: GMT 5.3 required, found GMT $version"
        exit 1
    fi
else
    if [[ $version == "$1"* ]]
    then
        echo "GMT $1 found"
    else
        echo "ERROR: GMT $1 required, found GMT $version"
        exit 1
    fi
fi
