#!/bin/bash
################################################################################
#                     Copyright (C) 2017 by Christian Meeßen                   #
#                                                                              #
#                         This file is part of Scripts                         #
#                                                                              #
#       GMTScripts is free software: you can redistribute it and/or modify     #
#     it under the terms of the GNU General Public License as published by     #
#           the Free Software Foundation version 3 of the License.             #
#                                                                              #
#      GMTScripts is distributed in the hope that it will be useful, but       #
#          WITHOUT ANY WARRANTY; without even the implied warranty of          #
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU       #
#                   General Public License for more details.                   #
#                                                                              #
#      You should have received a copy of the GNU General Public License       #
#       along with Scripts. If not, see <http://www.gnu.org/licenses/>.        #
################################################################################
# Default settings for gmt

version=`gmt --version`

tick='--'
if [[ $version == "5.5"* ]]
then
  tick=''
elif [[ $version == "5.4"* ]]
then
  tick=''
fi
gmt set "$tick"FONT_ANNOT_PRIMARY=6p \
        "$tick"FONT_ANNOT_SECONDARY=6p \
        "$tick"FONT_LABEL=7p \
        "$tick"FONT_TITLE=7p,Helvetica-Bold \
        "$tick"MAP_FRAME_PEN=0.5p \
        "$tick"MAP_LABEL_OFFSET=3p \
        "$tick"MAP_TICK_LENGTH_PRIMARY=2p \
        "$tick"MAP_TICK_LENGTH_SECONDARY=1p \
        "$tick"MAP_TITLE_OFFSET=7p \
        "$tick"PS_MEDIA=A4 \
        "$tick"PS_PAGE_ORIENTATION=portrait
